/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covers1624.ccintelli.gui;

import covers1624.ccintelli.launch.Launch;
import covers1624.ccintelli.module.Module;
import covers1624.ccintelli.module.ModuleEntry;
import covers1624.ccintelli.module.OrderEntry;
import covers1624.ccintelli.util.EnumLanguageLevel;
import covers1624.ccintelli.util.logging.LogHelper;
import covers1624.ccintelli.workspace.WorkspaceGenerator;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;

/**
 * @author brandon3055
 */
public class CCIntelliSetupMainWindow extends javax.swing.JFrame {

    private GroupNode rootNode;
    private DefaultTreeModel treeModel;
    private Module selectedModule = null;
    private ModuleNode rcNode = null;
    private DefaultListModel<String> srcListModel = new DefaultListModel<>();
    private DefaultListModel<String> corePluginListModel = new DefaultListModel<>();
    private DefaultListModel<String> vmArgListModel = new DefaultListModel<>();
    private LinkedList<ModuleEntry> selectedModuleEntries = new LinkedList<>();
    private PopupMenu treeRCMenu = new PopupMenu();
    private Map<String, GroupNode> groupNodes = new HashMap<>();
    private static final String MOVE_TO_SUB = "Move to module group";
    private static final String MOVE_TO_NEW_SUB = "Move to new module group";
    private static final String REMOVE_FROM_SUB = "Remove from module group";
    private boolean initialized = false;

    /**
     * Creates new form CCIntelliSetupMainWindow
     */
    public CCIntelliSetupMainWindow() {
        initComponents();
        setTitle("CCIntelliSetup! \\o/");
        setIconImage(Toolkit.getDefaultToolkit().createImage(CCIntelliSetupMainWindow.class.getResource("/CCIS_Icon.png")));

        workspaceDirField.setText(Launch.WORKSPACE.getAbsolutePath());
        moduleDirField.setText(Launch.MODULES.getAbsolutePath());
        runDirField.setText(Launch.PROJECT_RUN.getAbsolutePath());
        compilerOutDirField.setText(Launch.PROJECT_OUTPUT.getAbsolutePath());
        compilerSelector.setSelectedItem(Launch.COMPILER_SELECT);
        addNonNullAssertionsCheckbox.setSelected(Launch.NOT_NULL_ASSERTIONS);

        selectedModuleSourceList.setModel(srcListModel);
        corePluginList.setModel(corePluginListModel);
        vmArgList.setModel(vmArgListModel);

        for (EnumLanguageLevel level : EnumLanguageLevel.values()) {
            projectLangLevel.addItem(level.getGuiName());
            projectBytecodeLevel.addItem(level.getGuiName());
            moduleLanguageLevel.addItem(level.getGuiName());
            moduleBytecodeLevel.addItem(level.getGuiName());
        }

        projectLangLevel.setSelectedItem(GuiFields.projectLangLevel.getGuiName());
        projectBytecodeLevel.setSelectedItem(GuiFields.projectBytecodeLevel.getGuiName());

        setupModuleTree();
        setupDepTable();
        reloadModuleTree();
        reloadCorePluginList();
        reloadvmArgList();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        initialized = true;

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Launch.exit();
            }
        });

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new JPanel();
        mainTabbedPane = new JTabbedPane();
        setupPanel = new JPanel();
        setupLabel = new JLabel();
        leftSetupPanel = new JPanel();
        jLabel3 = new JLabel();
        workspaceDirField = new JTextField();
        workspaceDirSelect = new JButton();
        jLabel4 = new JLabel();
        moduleDirField = new JTextField();
        moduleDirSelect = new JButton();
        jLabel5 = new JLabel();
        runDirSelect = new JButton();
        runDirField = new JTextField();
        compilerOutDirSelect = new JButton();
        compilerOutDirField = new JTextField();
        jLabel6 = new JLabel();
        jLabel10 = new JLabel();
        jScrollPane3 = new JScrollPane();
        corePluginList = new JList<>();
        addCorePlugin = new JButton();
        removeCorePlugin = new JButton();
        editCorePlugin = new JButton();
        rightSetupPanel = new JPanel();
        jLabel2 = new JLabel();
        compilerSelector = new JComboBox<>();
        jLabel1 = new JLabel();
        addNonNullAssertionsCheckbox = new JCheckBox();
        jScrollPane5 = new JScrollPane();
        vmArgList = new JList<>();
        editVMArg = new JButton();
        addVMArg = new JButton();
        removeVMArg = new JButton();
        jLabel11 = new JLabel();
        jButton1 = new JButton();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        projectLangLevel = new JComboBox<>();
        projectBytecodeLevel = new JComboBox<>();
        modulePanel = new JPanel();
        leftModulePanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        moduleTree = new JTree();
        addModuleField = new JTextField();
        addModuleButton = new JButton();
        removeModuleButton = new JButton();
        jPanel1 = new JPanel();
        jLabel7 = new JLabel();
        selectedModuleDirectoryField = new JTextField();
        jLabel8 = new JLabel();
        jScrollPane2 = new JScrollPane();
        selectedModuleSourceList = new JList<>();
        addModuleSrc = new JButton();
        removeModuleSrc = new JButton();
        editModuleSrc = new JButton();
        jLabel9 = new JLabel();
        addModuleDep = new JButton();
        removeModuleDep = new JButton();
        jScrollPane4 = new JScrollPane();
        depTable = new JTable();
        jLabel14 = new JLabel();
        moduleLanguageLevel = new JComboBox<>();
        jLabel15 = new JLabel();
        moduleBytecodeLevel = new JComboBox<>();
        jMenuBar1 = new JMenuBar();
        fileMenu = new JMenu();
        importButton = new JMenuItem();
        exportButton = new JMenuItem();
        helpMenu = new JMenu();
        aboutMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        setupLabel.setHorizontalAlignment(SwingConstants.CENTER);
        setupLabel.setText("All the setup stuff.");
        setupLabel.setHorizontalTextPosition(SwingConstants.CENTER);

        leftSetupPanel.setBorder(BorderFactory.createEtchedBorder());

        jLabel3.setText("Workspace directory:");

        workspaceDirField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                workspaceDirFieldKeyReleased(evt);
            }
        });

        workspaceDirSelect.setText("...");
        workspaceDirSelect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                workspaceDirSelectActionPerformed(evt);
            }
        });

        jLabel4.setText("Module directory:");

        moduleDirField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                moduleDirFieldKeyReleased(evt);
            }
        });

        moduleDirSelect.setText("...");
        moduleDirSelect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                moduleDirSelectActionPerformed(evt);
            }
        });

        jLabel5.setText("Run directory:");

        runDirSelect.setText("...");
        runDirSelect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                runDirSelectActionPerformed(evt);
            }
        });

        runDirField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                runDirFieldKeyReleased(evt);
            }
        });

        compilerOutDirSelect.setText("...");
        compilerOutDirSelect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                compilerOutDirSelectActionPerformed(evt);
            }
        });

        compilerOutDirField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                compilerOutDirFieldKeyReleased(evt);
            }
        });

        jLabel6.setText("Compiler output directory:");

        jLabel10.setText("FML Core Plugins:");

        corePluginList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(corePluginList);

        addCorePlugin.setText("+");
        addCorePlugin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addCorePlugin(evt);
            }
        });

        removeCorePlugin.setText("-");
        removeCorePlugin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeCorePlugin(evt);
            }
        });

        editCorePlugin.setText("E");
        editCorePlugin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editCorePlugin(evt);
            }
        });

        GroupLayout leftSetupPanelLayout = new GroupLayout(leftSetupPanel);
        leftSetupPanel.setLayout(leftSetupPanelLayout);
        leftSetupPanelLayout.setHorizontalGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                                        .addComponent(workspaceDirField)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(workspaceDirSelect))
                                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                                        .addComponent(moduleDirField)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moduleDirSelect))
                                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                                        .addComponent(runDirField)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(runDirSelect))
                                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel10))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(GroupLayout.Alignment.TRAILING, leftSetupPanelLayout.createSequentialGroup()
                                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane3, GroupLayout.Alignment.LEADING)
                                                .addComponent(compilerOutDirField))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(compilerOutDirSelect)
                                                .addComponent(addCorePlugin)
                                                .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(removeCorePlugin, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editCorePlugin, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())
        );
        leftSetupPanelLayout.setVerticalGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(workspaceDirField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(workspaceDirSelect))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(moduleDirField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(moduleDirSelect))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(runDirField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(runDirSelect))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(compilerOutDirField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(compilerOutDirSelect))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(leftSetupPanelLayout.createSequentialGroup()
                                        .addComponent(addCorePlugin)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeCorePlugin)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editCorePlugin)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
        );

        rightSetupPanel.setBorder(BorderFactory.createEtchedBorder());

        jLabel2.setText("Compiler select:");

        compilerSelector.setModel(new DefaultComboBoxModel<>(new String[] { "Eclipse", "Javac" }));
        compilerSelector.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                compilerSelectorActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Not-Null Assertions");

        addNonNullAssertionsCheckbox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addNonNullAssertionsCheckboxActionPerformed(evt);
            }
        });

        vmArgList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(vmArgList);

        editVMArg.setText("E");
        editVMArg.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editVMArg(evt);
            }
        });

        addVMArg.setText("+");
        addVMArg.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addVMArg(evt);
            }
        });

        removeVMArg.setText("-");
        removeVMArg.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeVMArg(evt);
            }
        });

        jLabel11.setText("Optional VM Arguments:");

        jButton1.setText("Generate Workspace");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                generateWorkspaceButton(evt);
            }
        });

        jLabel12.setText("Project Language Level:");

        jLabel13.setText("Project Bytecode Level:");

        projectLangLevel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                selectProjectLangLevel(evt);
            }
        });

        projectBytecodeLevel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                selectProjectBytecodeLevel(evt);
            }
        });

        GroupLayout rightSetupPanelLayout = new GroupLayout(rightSetupPanel);
        rightSetupPanel.setLayout(rightSetupPanelLayout);
        rightSetupPanelLayout.setHorizontalGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(GroupLayout.Alignment.TRAILING, rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(addVMArg)
                                                .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(removeVMArg, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editVMArg, GroupLayout.Alignment.LEADING))))
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(compilerSelector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(projectBytecodeLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addNonNullAssertionsCheckbox))
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(projectLangLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
        );
        rightSetupPanelLayout.setVerticalGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(compilerSelector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(projectLangLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(projectBytecodeLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(addNonNullAssertionsCheckbox))
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rightSetupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(rightSetupPanelLayout.createSequentialGroup()
                                        .addComponent(addVMArg)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeVMArg)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editVMArg)
                                        .addGap(0, 18, Short.MAX_VALUE)))
                        .addContainerGap())
        );

        GroupLayout setupPanelLayout = new GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(setupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(setupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(setupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(setupPanelLayout.createSequentialGroup()
                                        .addComponent(leftSetupPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rightSetupPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addComponent(setupLabel, GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE))
                        .addContainerGap())
        );
        setupPanelLayout.setVerticalGroup(setupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setupLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(setupPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(rightSetupPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(leftSetupPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
        );

        mainTabbedPane.addTab("Setup", setupPanel);

        leftModulePanel.setBorder(BorderFactory.createEtchedBorder());

        DefaultMutableTreeNode treeNode1 = new DefaultMutableTreeNode("Modules");
        DefaultMutableTreeNode treeNode2 = new DefaultMutableTreeNode("Forge");
        treeNode1.add(treeNode2);
        moduleTree.setModel(new DefaultTreeModel(treeNode1));
        moduleTree.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                moduleTreeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(moduleTree);

        addModuleField.setToolTipText("New Module Name.");
        addModuleField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                addModuleFieldKeyPressed(evt);
            }
        });

        addModuleButton.setText("Add Module");
        addModuleButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addModuleButtonActionPerformed(evt);
            }
        });

        removeModuleButton.setText("Remove Module");
        removeModuleButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeModuleButtonActionPerformed(evt);
            }
        });

        GroupLayout leftModulePanelLayout = new GroupLayout(leftModulePanel);
        leftModulePanel.setLayout(leftModulePanelLayout);
        leftModulePanelLayout.setHorizontalGroup(leftModulePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(leftModulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftModulePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(leftModulePanelLayout.createSequentialGroup()
                                        .addComponent(addModuleButton)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(removeModuleButton))
                                .addComponent(addModuleField)
                                .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
        );
        leftModulePanelLayout.setVerticalGroup(leftModulePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(leftModulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addModuleField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftModulePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(addModuleButton)
                                .addComponent(removeModuleButton))
                        .addContainerGap())
        );

        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        jLabel7.setText("Directory:");

        selectedModuleDirectoryField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                selectedModuleDirectoryFieldKeyReleased(evt);
            }
        });

        jLabel8.setText("Src Directorys:");

        selectedModuleSourceList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectedModuleSourceList.setMinimumSize(new Dimension(20, 20));
        jScrollPane2.setViewportView(selectedModuleSourceList);

        addModuleSrc.setText("Add");
        addModuleSrc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addModuleSrcActionPerformed(evt);
            }
        });

        removeModuleSrc.setText("Remove");
        removeModuleSrc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeModuleSrcActionPerformed(evt);
            }
        });

        editModuleSrc.setText("Edit");
        editModuleSrc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editModuleSrcActionPerformed(evt);
            }
        });

        jLabel9.setText("Dependencies:");

        addModuleDep.setText("Add");
        addModuleDep.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addModuleDepActionPerformed(evt);
            }
        });

        removeModuleDep.setText("Remove");
        removeModuleDep.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeModuleDepActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setHorizontalScrollBar(null);

        depTable.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        depTable.setModel(depTablelModel = new DefaultTableModel(
                new Object [][] {
                        { new Boolean(false), null, null}
                },
                new String [] {
                        "Export", "Name", "Scope"
                }
        ) {
            Class[] types = new Class [] {
                    Boolean.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depTable.setToolTipText("");
        depTable.setColumnSelectionAllowed(true);
        depTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(depTable);
        depTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        if (depTable.getColumnModel().getColumnCount() > 0) {
            depTable.getColumnModel().getColumn(0).setMinWidth(60);
            depTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            depTable.getColumnModel().getColumn(0).setMaxWidth(60);
            depTable.getColumnModel().getColumn(2).setMinWidth(80);
            depTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            depTable.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel14.setText("Language Level:");

        moduleLanguageLevel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setModuleLanguage(evt);
            }
        });

        jLabel15.setText("Bytecode Level:");

        moduleBytecodeLevel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setModuleBytecode(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                                                .addComponent(selectedModuleDirectoryField)
                                                .addComponent(jScrollPane2)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel7)
                                                                .addComponent(jLabel8)
                                                                .addComponent(jLabel9)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(addModuleSrc)
                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(removeModuleSrc)))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(editModuleSrc, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(moduleLanguageLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(moduleBytecodeLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(addModuleDep)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(removeModuleDep)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedModuleDirectoryField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(addModuleSrc)
                                .addComponent(removeModuleSrc)
                                .addComponent(editModuleSrc))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(addModuleDep)
                                .addComponent(removeModuleDep))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(moduleLanguageLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(moduleBytecodeLevel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
        );

        GroupLayout modulePanelLayout = new GroupLayout(modulePanel);
        modulePanel.setLayout(modulePanelLayout);
        modulePanelLayout.setHorizontalGroup(modulePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(modulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(leftModulePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        modulePanelLayout.setVerticalGroup(modulePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, modulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(modulePanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(leftModulePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
        );

        mainTabbedPane.addTab("Module viewer tree", modulePanel);

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainTabbedPane, GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainTabbedPane, GroupLayout.Alignment.TRAILING)
        );

        fileMenu.setText("File");

        importButton.setText("Import Setup");
        importButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                importSetup(evt);
            }
        });
        fileMenu.add(importButton);

        exportButton.setText("Export Setup");
        exportButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exportSetup(evt);
            }
        });
        fileMenu.add(exportButton);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                displayAboutText(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // editor-fold defaultstate="collapsed" desc="Events">

    private void displayAboutText(ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "//TODO Put something here!!!\n-Gui written by brandon3055\n-Back End written by covers1624", "About", JOptionPane.INFORMATION_MESSAGE);
    }

    // <editor-fold defaultstate="collapsed" desc="Setup File Fields">

    //Launches the file picker for Workspace Directory
    private void workspaceDirSelectActionPerformed(ActionEvent evt) {
        workspaceDirField.setText(chooseDir(workspaceDirField.getText()));
        Launch.WORKSPACE = new File(workspaceDirField.getText());
    }

    //Launches the file picker for Module Directory
    private void moduleDirSelectActionPerformed(ActionEvent evt) {
        moduleDirField.setText(chooseDir(moduleDirField.getText()));
        Launch.MODULES = new File(moduleDirField.getText());
    }

    //Launches the file picker for Run Directory
    private void runDirSelectActionPerformed(ActionEvent evt) {
        runDirField.setText(chooseDir(runDirField.getText()));
        Launch.PROJECT_RUN = new File(runDirField.getText());
    }

    //Launches the file picker for Out Directory
    private void compilerOutDirSelectActionPerformed(ActionEvent evt) {
        compilerOutDirField.setText(chooseDir(compilerOutDirField.getText()));
        Launch.PROJECT_OUTPUT = new File(compilerOutDirField.getText());
    }

    private void workspaceDirFieldKeyReleased(KeyEvent evt) {
        Launch.WORKSPACE = new File(workspaceDirField.getText());
    }

    private void moduleDirFieldKeyReleased(KeyEvent evt) {
        Launch.MODULES = new File(moduleDirField.getText());
    }

    private void runDirFieldKeyReleased(KeyEvent evt) {
        Launch.PROJECT_RUN = new File(runDirField.getText());
    }

    private void compilerOutDirFieldKeyReleased(KeyEvent evt) {
        Launch.PROJECT_OUTPUT = new File(compilerOutDirField.getText());
    }

    public void reloadCorePluginList() {
        corePluginListModel.clear();

        for (String plugin : GuiFields.fmlCorePlugins) {
            corePluginListModel.addElement(plugin);
        }
    }

    private void addCorePlugin(ActionEvent evt) {
        String dir = JOptionPane.showInputDialog(this, "Enter new core plugin");
        if (dir == null || dir.isEmpty()) {
            return;
        }

        if (GuiFields.fmlCorePlugins.contains(dir)) {
            JOptionPane.showMessageDialog(this, "That plugin already exists!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GuiFields.fmlCorePlugins.add(dir);
        reloadCorePluginList();
    }

    private void removeCorePlugin(ActionEvent evt) {
        int index = corePluginList.getSelectedIndex();
        if (index == -1 || index > corePluginListModel.size()) {
            JOptionPane.showMessageDialog(this, "No core plugin selected!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GuiFields.fmlCorePlugins.remove(corePluginListModel.get(index));
        reloadCorePluginList();
    }

    private void editCorePlugin(ActionEvent evt) {
        int index = corePluginList.getSelectedIndex();
        if (index == -1 || index > corePluginListModel.size()) {
            JOptionPane.showMessageDialog(this, "Please select core plugin to edit", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newDir = JOptionPane.showInputDialog(this, "Edit Core Plugin", corePluginListModel.get(index));
        if (newDir == null || newDir.isEmpty()) {
            return;
        }

        GuiFields.fmlCorePlugins.remove(corePluginListModel.get(index));
        GuiFields.fmlCorePlugins.add(newDir);
        reloadCorePluginList();
    }

    public void reloadvmArgList() {
        vmArgListModel.clear();

        for (String plugin : GuiFields.vmArgs) {
            vmArgListModel.addElement(plugin);
        }
    }

    private void addVMArg(ActionEvent evt) {
        String dir = JOptionPane.showInputDialog(this, "Enter VM Argument");
        if (dir == null || dir.isEmpty()) {
            return;
        }

        if (GuiFields.vmArgs.contains(dir)) {
            JOptionPane.showMessageDialog(this, "That VM Argument exists!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GuiFields.vmArgs.add(dir);
        reloadvmArgList();
    }

    private void removeVMArg(ActionEvent evt) {
        int index = vmArgList.getSelectedIndex();
        if (index == -1 || index > vmArgListModel.size()) {
            JOptionPane.showMessageDialog(this, "No VM Argument selected!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GuiFields.vmArgs.remove(vmArgListModel.get(index));
        reloadvmArgList();
    }

    private void editVMArg(ActionEvent evt) {
        int index = vmArgList.getSelectedIndex();
        if (index == -1 || index > vmArgListModel.size()) {
            JOptionPane.showMessageDialog(this, "Please select an argument to edit", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newDir = JOptionPane.showInputDialog(this, "Edit VM Argument", vmArgListModel.get(index));
        if (newDir == null || newDir.isEmpty()) {
            return;
        }

        GuiFields.vmArgs.remove(vmArgListModel.get(index));
        GuiFields.vmArgs.add(newDir);
        reloadvmArgList();
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Compiler & Non-Null">

    private void addNonNullAssertionsCheckboxActionPerformed(ActionEvent evt) {
        Launch.NOT_NULL_ASSERTIONS = addNonNullAssertionsCheckbox.isSelected();
    }

    private void compilerSelectorActionPerformed(ActionEvent evt) {
        Launch.COMPILER_SELECT = compilerSelector.getSelectedItem().toString();
    }

    private void selectProjectLangLevel(ActionEvent evt) {
        if (!initialized) {
            return;
        }
        GuiFields.projectLangLevel = findLevel(projectLangLevel.getSelectedItem().toString());
    }

    private void selectProjectBytecodeLevel(ActionEvent evt) {
        if (!initialized) {
            return;
        }
        GuiFields.projectBytecodeLevel = findLevel(projectBytecodeLevel.getSelectedItem().toString());
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Module Tree">

    private void moduleTreeMousePressed(MouseEvent e) {
        int selRow = moduleTree.getRowForLocation(e.getX(), e.getY());
        TreePath selPath = moduleTree.getPathForLocation(e.getX(), e.getY());
        if (selRow != -1 && selPath != null) {
            Object component = selPath.getLastPathComponent();

            //Left Click
            if (e.getButton() == 1 && e.getClickCount() == 1) {
                if (component instanceof ModuleNode) {
                    moduleSelected(((ModuleNode) component).module);
                }
            }
            //Right Click
            else if (e.getButton() == 3) {
                treeRCMenu.removeAll();
                if (component instanceof ModuleNode) {
                    if (((ModuleNode) component).module.NAME.equals("Forge")) {
                        return;
                    }

                    rcNode = (ModuleNode) component;

                    if (!groupNodes.isEmpty()) {
                        treeRCMenu.add(MOVE_TO_SUB);
                    }

                    treeRCMenu.add(MOVE_TO_NEW_SUB);

                    if (!((ModuleNode) component).module.GROUP.isEmpty()) {
                        treeRCMenu.add(REMOVE_FROM_SUB);
                    }

                    treeRCMenu.show(moduleTree, e.getX(), e.getY());
                }
            }

            if (moduleTree.getEditingPath() != null) {
                String editing = moduleTree.getEditingPath().getLastPathComponent().toString();
                if (editing.equals("Modules") || editing.equals("Forge")) {
                    moduleTree.stopEditing();
                }
            }
        }
    }

    private void addModuleButtonActionPerformed(ActionEvent evt) {
        if (addModuleField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You must first enter a name for this module!", "Error", JOptionPane.WARNING_MESSAGE);
            reloadModuleTree();
            return;
        }

        for (Module module : GuiFields.modules) {
            if (module.NAME.equals(addModuleField.getText())) {
                JOptionPane.showMessageDialog(this, "There is already a module with that name!\nPlease choose another name or rename the existing module.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        Module module = new Module();
        module.NAME = addModuleField.getText();
        module.CONTENT_ROOT = new File(Launch.SETUP_DIR, module.NAME);
        module.sourceFolders = GuiFields.findModuleSrc(module);
        module.langLevel = GuiFields.projectLangLevel;
        module.bytecodeLevel = GuiFields.projectBytecodeLevel;
        GuiFields.onModuleAdded(module);
        reloadModuleTree();
        addModuleField.setText("");
    }

    private void addModuleFieldKeyPressed(KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            addModuleButtonActionPerformed(null);
        }
    }

    private void removeModuleButtonActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            selectedModuleDirectoryField.setText("");
            return;
        }

        if (selectedModule.NAME.equals("Forge")) {
            JOptionPane.showMessageDialog(this, "You can not delete the forge module!!!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the module\n" + selectedModule.NAME + "?", "Delete Module?", JOptionPane.YES_NO_OPTION) == 1) {
            return;
        }

        GuiFields.modules.remove(selectedModule);
        reloadModuleTree();
        moduleSelected(null);
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Edit Module">

    private void selectedModuleDirectoryFieldKeyReleased(KeyEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            selectedModuleDirectoryField.setText("");
            return;
        }

        selectedModule.CONTENT_ROOT = new File(Launch.SETUP_DIR, selectedModuleDirectoryField.getText());
    }

    private void addModuleSrcActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dir = JOptionPane.showInputDialog(this, "Enter Src Directory");
        if (dir == null || dir.isEmpty()) {
            return;
        }

        if (selectedModule.sourceFolders.contains(dir)) {
            JOptionPane.showMessageDialog(this, "That Src already exists!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedModule.sourceFolders.add(dir);
        moduleSelected(selectedModule);
    }

    private void removeModuleSrcActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int index = selectedModuleSourceList.getSelectedIndex();
        if (index == -1 || index > srcListModel.size()) {
            JOptionPane.showMessageDialog(this, "Please select source dir to remove", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedModule.sourceFolders.remove(srcListModel.get(index));
        moduleSelected(selectedModule);
    }

    private void editModuleSrcActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int index = selectedModuleSourceList.getSelectedIndex();
        if (index == -1 || index > srcListModel.size()) {
            JOptionPane.showMessageDialog(this, "Please select source dir to edit", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newDir = JOptionPane.showInputDialog(this, "Edit Src Directory", srcListModel.get(index));
        if (newDir == null || newDir.isEmpty()) {
            return;
        }

        selectedModule.sourceFolders.remove(srcListModel.get(index));
        selectedModule.sourceFolders.add(newDir);
        moduleSelected(selectedModule);
    }

    private void addModuleDepActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.List<String> selection = new ArrayList<>();

        for (Module module : GuiFields.modules) {
            boolean canAdd = true;
            for (OrderEntry entry : selectedModule.orderEntries) {
                if (entry instanceof ModuleEntry && ((ModuleEntry) entry).NAME.equals(module.NAME)) {
                    canAdd = false;
                }
            }

            if (canAdd && !module.NAME.equals(selectedModule.NAME)) {
                selection.add(module.NAME);
            }
        }

        if (selection.size() == 0) {
            JOptionPane.showMessageDialog(this, "There are no modules that can be added as a dependency.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dep = (String) JOptionPane.showInputDialog(this, "Please select a module", "Select Module", JOptionPane.QUESTION_MESSAGE, null, selection.toArray(), selection.get(0));
        if (dep == null || dep.isEmpty()) {
            return;
        }

        selectedModule.orderEntries.add(new ModuleEntry(dep, false, OrderEntry.Scope.PROVIDED));
        moduleSelected(selectedModule);
    }

    private void removeModuleDepActionPerformed(ActionEvent evt) {
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int row = depTable.getSelectedRow();
        if (row == -1 || row >= selectedModuleEntries.size()) {
            JOptionPane.showMessageDialog(this, "Please select a dep!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedModuleEntries.get(row).NAME.equals("Forge")) {
            JOptionPane.showMessageDialog(this, "You can not remove forge as a dependency!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        depTable.updateUI();
        selectedModule.orderEntries.remove(selectedModuleEntries.get(row));
        moduleSelected(selectedModule);
    }

    private void setModuleLanguage(ActionEvent evt) {
        if (!initialized) {
            return;
        }
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedModule.langLevel = findLevel(moduleLanguageLevel.getSelectedItem().toString());
    }

    private void setModuleBytecode(ActionEvent evt) {
        if (!initialized) {
            return;
        }
        if (selectedModule == null || !GuiFields.modules.contains(selectedModule)) {
            JOptionPane.showMessageDialog(this, "Please select a module!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedModule.bytecodeLevel = findLevel(moduleBytecodeLevel.getSelectedItem().toString());
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="File">

    private void importSetup(ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter;
        chooser.addChoosableFileFilter(filter = new FileNameExtensionFilter("JSON (.json)", "json"));
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(Launch.SAVES_DIR);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (!chooser.getSelectedFile().exists()) {
                JOptionPane.showMessageDialog(this, "That file does not exist!", "File Not Found", JOptionPane.ERROR_MESSAGE);
                return;
            }
            GuiFields.importSetup(chooser.getSelectedFile());
            JOptionPane.showMessageDialog(this, "Successfully imported setup!");
            reloadModuleTree();
            reloadCorePluginList();
        }
    }

    private void exportSetup(ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter;
        chooser.addChoosableFileFilter(filter = new FileNameExtensionFilter("JSON (.json)", "json"));
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(Launch.SAVES_DIR);

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile().exists()) {
                if (JOptionPane.showConfirmDialog(this, "The selected file already exists!\nDo you wish to overwrite it?", "Overwrite?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 1) {
                    return;
                }
                GuiFields.exportSetup(chooser.getSelectedFile());
                JOptionPane.showMessageDialog(this, "Successfully exported setup!");
                return;
            }

            String path = chooser.getSelectedFile().getAbsolutePath();

            if (chooser.getFileFilter() == filter && !chooser.getSelectedFile().getAbsolutePath().endsWith(".json")) {
                GuiFields.exportSetup(new File(path + ".json"));
                JOptionPane.showMessageDialog(this, "Successfully exported setup!");
            } else {
                GuiFields.exportSetup(chooser.getSelectedFile());
                JOptionPane.showMessageDialog(this, "Successfully exported setup!");
            }
            reloadModuleTree();
            reloadCorePluginList();
        }
    }

    // </editor-fold>

    private void generateWorkspaceButton(ActionEvent evt) {

        if (!new File(Launch.SETUP_DIR, "Forge/src").exists()) {
            ArrayList<String> list = new ArrayList<>();
            list.add("It appears forge is missing from: " + Launch.FORGE.getAbsolutePath());
            list.add("Please clone forge from <a href=\"https://github.com/MinecraftForge/MinecraftForge\">here</a>.");
            list.add("Make sure Forge's src dir is inside the above folder and not in a sub directory.");
            InformationDialog infoDialog = new InformationDialog("Forge Missing", this, list);
            infoDialog.dispaly();
            return;
        }

        ProcessingDialog dialog = new ProcessingDialog(this, "Setting up the workspace, \nClick the button bellow to see the console if you have closed it.");
        final String projectName = JOptionPane.showInputDialog("Enter a name for the Intellij project..", Launch.SETUP_DIR.getName());
        if (projectName == null || projectName.isEmpty()) {
            LogHelper.info("Setup canceled.");
            return;
        }
        Launch.scheduleTask(() -> WorkspaceGenerator.generateWorkspace(projectName));
        Launch.scheduleTask(dialog::dispose);
        dialog.setVisible(true);
    }

    // /editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Misc">

    public String chooseDir(String defaultDir) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File selectedFile = new File(defaultDir);

        if (selectedFile.exists()) {
            chooser.setCurrentDirectory(selectedFile);
        }

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
        }

        return selectedFile.getAbsolutePath();
    }

    private void setupModuleTree() {
        moduleTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        rootNode = new GroupNode("Modules");
        treeModel = new DefaultTreeModel(rootNode);
        moduleTree.setModel(treeModel);
        moduleTree.setEditable(false);

        add(treeRCMenu);
        treeRCMenu.addActionListener(this::treeMenuAction);

//        treeModel.addTreeModelListener(new TreeModelListener() {
//            @Override
//            public void treeNodesChanged(TreeModelEvent e) {
//                if (e.getChildIndices() == null) {
//                    return;
//                }
//
//                DefaultMutableTreeNode n = (DefaultMutableTreeNode) e.getTreePath().getLastPathComponent();
//                ModuleNode node = (ModuleNode) n.getChildAt(e.getChildIndices()[0]);
//
//                String newName = node.getUserObject().toString();
//                if (!newName.equals(node.module.NAME)) {
//                    boolean cancelRename = false;
//                    for (Module module : GuiFields.modules) {
//                        if (module.NAME.equals(newName)) {
//                            cancelRename = true;
//                            break;
//                        }
//                    }
//
//                    if (cancelRename) {
//                        reloadModuleTree();
//                        JOptionPane.showMessageDialog(CCIntelliSetupMainWindow.this, "There is already a module with that name!\nPlease choose another name or rename the existing module.", "Error", JOptionPane.WARNING_MESSAGE);
//                    }
//                    else {
//                        LogHelper.info("Renaming module: " + node.module.NAME + " -> " + newName);
//                        node.module.NAME = newName;
//                    }
//                }
//            }
//
//            @Override
//            public void treeNodesInserted(TreeModelEvent e) {
//
//            }
//
//            @Override
//            public void treeNodesRemoved(TreeModelEvent e) {
//
//            }
//
//            @Override
//            public void treeStructureChanged(TreeModelEvent e) {
//
//            }
//        });

        selectedModuleSourceList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (!new File(value.toString()).exists()) {
                    setBackground(Color.RED);
                }
                return c;
            }
        });

    }

    private void setupDepTable() {
        depTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableColumn scopeColumn = depTable.getColumnModel().getColumn(2);
        JComboBox comboBox = new JComboBox();
        comboBox.addItem(OrderEntry.Scope.COMPILE);
        comboBox.addItem(OrderEntry.Scope.TEST);
        comboBox.addItem(OrderEntry.Scope.RUNTIME);
        comboBox.addItem(OrderEntry.Scope.PROVIDED);
        scopeColumn.setCellEditor(new DefaultCellEditor(comboBox));

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        scopeColumn.setCellRenderer(centerRenderer);

        depTable.getModel().addTableModelListener(e -> {
            int column = e.getColumn();
            int row = e.getFirstRow();
            if (column != -1 && selectedModule != null && GuiFields.modules.contains(selectedModule)) {
                ModuleEntry entry = selectedModuleEntries.get(row);

                if (column == 0) {
                    entry.export = (boolean) depTablelModel.getValueAt(row, column);
                }
                else if (column == 1) {
                    entry.NAME = (String) depTablelModel.getValueAt(row, column);
                }
                else if (column == 2) {
                    entry.scope = (OrderEntry.Scope) depTablelModel.getValueAt(row, column);
                }
            }
        });

    }

    public void reloadModuleTree() {
//        Enumeration children = rootNode.children();
//        while (children.hasMoreElements()) {
//            LogHelper.info(children.nextElement());
//        }
        rootNode.removeAllChildren();
        groupNodes.clear();

        for (Module module : GuiFields.modules) {
            ModuleNode moduleNode = new ModuleNode(module);

            if (!module.GROUP.isEmpty()) {
                if (groupNodes.containsKey(module.GROUP)) {
                    groupNodes.get(module.GROUP).add(moduleNode);
                }
                else {
                    GroupNode node = createGroupChain(module.GROUP, "");
                    if (node.getParent() == null) {
                        rootNode.add(node);
                    }
                    groupNodes.get(module.GROUP).add(moduleNode);
                }
            }
            else {
                rootNode.add(moduleNode);
            }
        }

        treeModel.reload();
        for (int i = 0; i < moduleTree.getRowCount(); i++) {
            moduleTree.expandRow(i);
        }
    }

    private GroupNode createGroupChain(String group, String parentGroup) {
        GroupNode node = null;
        String name = group.contains("/") ? group.substring(0, group.indexOf("/")) : group;

        if (groupNodes.containsKey(group)) {
            node = groupNodes.get(group);
        }
        else {
            for (GroupNode node1 : groupNodes.values()) {
                if (node1.group.equals(name)) {
                    node = node1;
                }
            }

            if (node == null) {
                node = new GroupNode(name);
                groupNodes.put(parentGroup + name, node);
                if (groupNodes.containsKey(parentGroup)) {
                    groupNodes.get(parentGroup).add(node);
                }
            }
        }

        if (group.contains("/")) {
            GroupNode child = createGroupChain(group.substring(group.indexOf("/") + 1), parentGroup + name + "/");
            node.add(child);
        }

        return node;
    }

    public void moduleSelected(Module module) {
        selectedModule = module;
        selectedModuleDirectoryField.setText("");
        srcListModel.clear();
        selectedModuleEntries.clear();
        while (depTablelModel.getRowCount() > 0) {
            depTablelModel.removeRow(0);
        }

        if (module == null) {
            return;
        }

        moduleLanguageLevel.setSelectedItem(module.langLevel.getGuiName());
        moduleBytecodeLevel.setSelectedItem(module.bytecodeLevel.getGuiName());

        selectedModuleDirectoryField.setText(module.CONTENT_ROOT.getAbsolutePath());
        for (String src : module.sourceFolders) {
            srcListModel.addElement(src);
        }

        for (OrderEntry dep : module.orderEntries) {
            if (dep instanceof ModuleEntry) {
                depTablelModel.addRow(new Object[]{dep.export, ((ModuleEntry) dep).NAME, dep.scope});
                selectedModuleEntries.add((ModuleEntry) dep);
            }
        }
    }

    private void treeMenuAction(ActionEvent event) {
        String action = event.getActionCommand();
        if (action.equals(MOVE_TO_NEW_SUB)) {
            String newSub = JOptionPane.showInputDialog(this, "Enter new sub module name:");

            if (newSub == null || newSub.isEmpty()) {
                JOptionPane.showMessageDialog(this, "You must enter a valid name", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (rcNode.module.GROUP.isEmpty()) {
                rcNode.module.GROUP = newSub;
            }
            else {
                rcNode.module.GROUP += "/" + newSub;
            }
            reloadModuleTree();
        }
        else if (action.equals(REMOVE_FROM_SUB)) {
            LogHelper.info(rcNode.module.GROUP);
            if (rcNode.module.GROUP.contains("/")) {
                String g = rcNode.module.GROUP;
                rcNode.module.GROUP = g.substring(0, g.lastIndexOf("/"));
            }
            else {
                rcNode.module.GROUP = "";
            }
            reloadModuleTree();
        }
        else if (action.equals(MOVE_TO_SUB)) {
            Object group = JOptionPane.showInputDialog(this, "Select Sub Group", "Select Group", JOptionPane.PLAIN_MESSAGE, null, groupNodes.keySet().toArray(), groupNodes.keySet().toArray()[0]);
            if (group == null) {
                return;
            }
            rcNode.module.GROUP = group.toString();
            reloadModuleTree();
        }
    }

    private EnumLanguageLevel findLevel(String guiName) {
        for (EnumLanguageLevel level : EnumLanguageLevel.values()) {
            if (level.getGuiName().equals(guiName)) {
                return level;
            }
        }
        return EnumLanguageLevel.JDK_1_6;
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify                     
    private JMenuItem aboutMenuItem;
    private JButton addCorePlugin;
    private JButton addModuleButton;
    private JButton addModuleDep;
    private JTextField addModuleField;
    private JButton addModuleSrc;
    private JCheckBox addNonNullAssertionsCheckbox;
    private JButton addVMArg;
    private JTextField compilerOutDirField;
    private JButton compilerOutDirSelect;
    private JComboBox<String> compilerSelector;
    private JList<String> corePluginList;
    private DefaultTableModel depTablelModel;
    private JTable depTable;
    private JButton editCorePlugin;
    private JButton editModuleSrc;
    private JButton editVMArg;
    private JMenuItem exportButton;
    private JMenu fileMenu;
    private JMenu helpMenu;
    private JMenuItem importButton;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JPanel leftModulePanel;
    private JPanel leftSetupPanel;
    private JPanel mainPanel;
    private JTabbedPane mainTabbedPane;
    private JComboBox<String> moduleBytecodeLevel;
    private JTextField moduleDirField;
    private JButton moduleDirSelect;
    private JComboBox<String> moduleLanguageLevel;
    private JPanel modulePanel;
    private JTree moduleTree;
    private JComboBox<String> projectBytecodeLevel;
    private JComboBox<String> projectLangLevel;
    private JButton removeCorePlugin;
    private JButton removeModuleButton;
    private JButton removeModuleDep;
    private JButton removeModuleSrc;
    private JButton removeVMArg;
    private JPanel rightSetupPanel;
    private JTextField runDirField;
    private JButton runDirSelect;
    private JTextField selectedModuleDirectoryField;
    private JList<String> selectedModuleSourceList;
    private JLabel setupLabel;
    private JPanel setupPanel;
    private JList<String> vmArgList;
    private JTextField workspaceDirField;
    private JButton workspaceDirSelect;
    // End of variables declaration                   
    // </editor-fold>
}
//Export file browser. Current directory no file name
