package covers1624.ccintelli.gui;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class ProcessingDialog extends JDialog {

    /**
     * Creates new form ProcessingDialog
     */
    public ProcessingDialog(java.awt.Frame parent, String message) {
        super(parent, true);
        initComponents();
        jTextField1.setText(message);

        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new JButton();
        jTextField1 = new JTextField();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Open Consol");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                openConsoleButton(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(JTextField.CENTER);
        jTextField1.setText("jTextField1");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField1)
                                .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                        .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>

    private void openConsoleButton(ActionEvent evt) {

    }

    /**
     * Called when the user attempts to close the window
     */
    private void formWindowClosing(WindowEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify                     
    private JButton jButton1;
    private JTextField jTextField1;
    // End of variables declaration                   
}